# NumPy Introduction

NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [1]:
import numpy as np

print("NumPy imported successfully!")

NumPy imported successfully!


## Creating Arrays from Lists

Python lists are flexible but not optimized for numerical computations. NumPy arrays provide better performance and additional functionality.

In [2]:
a_array = [1, 2, 3, 4, 5]
print(f"a_array: {a_array}")
print("Indexing: a_array[2] =", a_array[2])
print("Slicing: a_array[1:3] =", a_array[1:3])
print("Reverse: a_array[::-1] =", a_array[::-1])
print("Every other: a_array[::2] =", a_array[::2])

np_array = np.array([1, 2, 3, 4, 5])
print(f"\nnp_array: {np_array}")
print(f"type(np_array): {type(np_array)}")
print(f"Element type: type(np_array[2]) = {type(np_array[2])}")
print(f"Slicing: np_array[1:3] = {np_array[1:3]}")
print(f"Reverse: np_array[:-2] = {np_array[:-2]}")
np_array[2] = 100
print(f"After modification: np_array = {np_array}")

a_array: [1, 2, 3, 4, 5]
Indexing: a_array[2] = 3
Slicing: a_array[1:3] = [2, 3]
Reverse: a_array[::-1] = [5, 4, 3, 2, 1]
Every other: a_array[::2] = [1, 3, 5]

np_array: [1 2 3 4 5]
type(np_array): <class 'numpy.ndarray'>
Element type: type(np_array[2]) = <class 'numpy.int64'>
Slicing: np_array[1:3] = [2 3]
Reverse: np_array[:-2] = [1 2 3]
After modification: np_array = [  1   2 100   4   5]


## Multidimensional Arrays

NumPy supports multi-dimensional arrays, which are essential for matrices and higher-dimensional data structures.

In [3]:
np_mdarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D array:\n{np_mdarray}")
print(f"Shape: {np_mdarray.shape}")
print(f"Dimensions: {np_mdarray.ndim}")
print(f"Size: {np_mdarray.size}")
print(f"Data type: {np_mdarray.dtype}")

# Mixed types
np_mdarray_mixed = np.array([[1, 2, 3], [4, "Hello", 6], [7, 8, 9]])
print(f"\nMixed type array:\n{np_mdarray_mixed}")
print(f"Data type: {np_mdarray_mixed.dtype}")
print(f"Element [1][1]: {np_mdarray_mixed[1][1]} (type: {type(np_mdarray_mixed[1][1])})")

# Explicit dtype
np_mdarray_int = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int64)
print(f"\nExplicit int64 array:\n{np_mdarray_int}")
print(f"Data type: {np_mdarray_int.dtype}")

2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64

Mixed type array:
[['1' '2' '3']
 ['4' 'Hello' '6']
 ['7' '8' '9']]
Data type: <U21
Element [1][1]: Hello (type: <class 'numpy.str_'>)

Explicit int64 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: int64
