# Advanced NumPy Techniques

This notebook covers advanced NumPy features and techniques that are essential for high-performance numerical computing, data science, and scientific computing applications.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

print("NumPy version:", np.__version__)
print("Advanced NumPy techniques ready!")

NumPy version: 2.3.0
Advanced NumPy techniques ready!


## Structured Arrays

Structured arrays allow you to create array data types that mimic database records or C-style structs, with named fields of different data types.

In [2]:
# Structured Arrays - Basic Usage
print("=== Structured Arrays: Basic Usage ===")

# Define a structured data type (like a database table)
employee_dtype = np.dtype([
    ('name', 'U20'),      # Unicode string, max 20 chars
    ('age', 'i4'),        # 32-bit integer
    ('salary', 'f8'),     # 64-bit float
    ('department', 'U15') # Unicode string, max 15 chars
])

print("Employee data type:")
print(employee_dtype)
print(f"Field names: {employee_dtype.names}")
print(f"Field descriptions: {[field[1] for field in employee_dtype.descr]}")
print()

# Create structured array with employee data
employees = np.array([
    ('Alice Johnson', 28, 75000.0, 'Engineering'),
    ('Bob Smith', 35, 82000.0, 'Marketing'),
    ('Carol Davis', 42, 95000.0, 'Engineering'),
    ('David Wilson', 31, 68000.0, 'Sales'),
    ('Eva Brown', 29, 72000.0, 'HR')
], dtype=employee_dtype)

print("Employee structured array:")
print(employees)
print(f"Shape: {employees.shape}")
print(f"Data type: {employees.dtype}")
print()

=== Structured Arrays: Basic Usage ===
Employee data type:
[('name', '<U20'), ('age', '<i4'), ('salary', '<f8'), ('department', '<U15')]
Field names: ('name', 'age', 'salary', 'department')
Field descriptions: ['<U20', '<i4', '<f8', '<U15']

Employee structured array:
[('Alice Johnson', 28, 75000., 'Engineering')
 ('Bob Smith', 35, 82000., 'Marketing')
 ('Carol Davis', 42, 95000., 'Engineering')
 ('David Wilson', 31, 68000., 'Sales') ('Eva Brown', 29, 72000., 'HR')]
Shape: (5,)
Data type: [('name', '<U20'), ('age', '<i4'), ('salary', '<f8'), ('department', '<U15')]



In [3]:
# Accessing structured array data
print("=== Accessing Structured Array Data ===")

# Access individual fields
print("Employee names:", employees['name'])
print("Employee ages:", employees['age'])
print("Employee salaries:", employees['salary'])
print("Departments:", employees['department'])
print()

# Access individual records
print("First employee record:")
print(employees[0])
print(f"Type: {type(employees[0])}")
print()

# Access specific field of specific record
print(f"Alice's salary: ${employees[0]['salary']:,}")
print(f"Bob's age: {employees[1]['age']} years")
print()

# Boolean indexing with structured arrays
engineering_mask = employees['department'] == 'Engineering'
print("Engineering employees:")
print(employees[engineering_mask])
print()

# Conditional operations
high_earners = employees[employees['salary'] > 80000]
print("High earners (salary > $80,000):")
print(high_earners['name'])
print(f"Average high earner salary: ${high_earners['salary'].mean():,.0f}")

=== Accessing Structured Array Data ===
Employee names: ['Alice Johnson' 'Bob Smith' 'Carol Davis' 'David Wilson' 'Eva Brown']
Employee ages: [28 35 42 31 29]
Employee salaries: [75000. 82000. 95000. 68000. 72000.]
Departments: ['Engineering' 'Marketing' 'Engineering' 'Sales' 'HR']

First employee record:
('Alice Johnson', 28, 75000.0, 'Engineering')
Type: <class 'numpy.void'>

Alice's salary: $75,000.0
Bob's age: 35 years

Engineering employees:
[('Alice Johnson', 28, 75000., 'Engineering')
 ('Carol Davis', 42, 95000., 'Engineering')]

High earners (salary > $80,000):
['Bob Smith' 'Carol Davis']
Average high earner salary: $88,500


In [4]:
# Operations on structured arrays
print("=== Operations on Structured Arrays ===")

# Calculate statistics by field
print("Salary statistics:")
print(f"  Mean: ${employees['salary'].mean():,.0f}")
print(f"  Median: ${np.median(employees['salary']):,.0f}")
print(f"  Min: ${employees['salary'].min():,.0f}")
print(f"  Max: ${employees['salary'].max():,.0f}")
print()

# Group operations (manual grouping example)
departments = np.unique(employees['department'])
print("Department statistics:")
for dept in departments:
    dept_employees = employees[employees['department'] == dept]
    avg_salary = dept_employees['salary'].mean()
    avg_age = dept_employees['age'].mean()
    count = len(dept_employees)
    print(f"  {dept}: {count} employees, avg salary ${avg_salary:,.0f}, avg age {avg_age:.1f}")
print()

# Modifying structured array data
print("Before salary increase:")
print(f"Alice's salary: ${employees[0]['salary']:,.0f}")

# Give Alice a 10% raise
employees[0]['salary'] *= 1.10
print(f"After 10% raise: ${employees[0]['salary']:,.0f}")
print()

# Add new employee (need to create new array)
new_employee = np.array([('Frank Miller', 38, 78000.0, 'Finance')], dtype=employee_dtype)
employees = np.concatenate([employees, new_employee])
print("After adding new employee:")
print(f"Total employees: {len(employees)}")
print("Last employee:", employees[-1]['name'])

=== Operations on Structured Arrays ===
Salary statistics:
  Mean: $78,400
  Median: $75,000
  Min: $68,000
  Max: $95,000

Department statistics:
  Engineering: 2 employees, avg salary $85,000, avg age 35.0
  HR: 1 employees, avg salary $72,000, avg age 29.0
  Marketing: 1 employees, avg salary $82,000, avg age 35.0
  Sales: 1 employees, avg salary $68,000, avg age 31.0

Before salary increase:
Alice's salary: $75,000
After 10% raise: $82,500

After adding new employee:
Total employees: 6
Last employee: Frank Miller


In [5]:
# Advanced structured arrays: nested dtypes
print("=== Advanced: Nested Structured Arrays ===")

# Create a more complex dtype with nested structure
complex_dtype = np.dtype([
    ('id', 'i4'),
    ('personal', [
        ('name', 'U20'),
        ('age', 'i2'),
        ('email', 'U30')
    ]),
    ('work', [
        ('department', 'U15'),
        ('position', 'U20'),
        ('salary', 'f8'),
        ('start_date', 'U10')
    ])
])

print("Complex nested dtype:")
print(complex_dtype)
print()

# Create data for nested structure
complex_data = np.array([
    (1, 
     ('Alice Johnson', 28, 'alice@company.com'),
     ('Engineering', 'Senior Developer', 85000.0, '2020-03-15')
    ),
    (2,
     ('Bob Smith', 35, 'bob@company.com'),
     ('Marketing', 'Marketing Manager', 78000.0, '2019-07-22')
    )
], dtype=complex_dtype)

print("Nested structured array:")
print(complex_data)
print()

# Access nested fields
print("Accessing nested fields:")
print(f"Alice's email: {complex_data[0]['personal']['email']}")
print(f"Bob's position: {complex_data[1]['work']['position']}")
print(f"Alice's salary: ${complex_data[0]['work']['salary']:,.0f}")
print()

# Calculate average salary from nested structure
avg_salary = complex_data['work']['salary'].mean()
print(f"Average salary: ${avg_salary:,.0f}")

=== Advanced: Nested Structured Arrays ===
Complex nested dtype:
[('id', '<i4'), ('personal', [('name', '<U20'), ('age', '<i2'), ('email', '<U30')]), ('work', [('department', '<U15'), ('position', '<U20'), ('salary', '<f8'), ('start_date', '<U10')])]

Nested structured array:
[(1, ('Alice Johnson', 28, 'alice@company.com'), ('Engineering', 'Senior Developer', 85000., '2020-03-15'))
 (2, ('Bob Smith', 35, 'bob@company.com'), ('Marketing', 'Marketing Manager', 78000., '2019-07-22'))]

Accessing nested fields:
Alice's email: alice@company.com
Bob's position: Marketing Manager
Alice's salary: $85,000

Average salary: $81,500


In [6]:
# Performance comparison: structured arrays vs regular arrays
print("=== Performance: Structured Arrays vs Regular Arrays ===")

import time

# Create test data
n = 100000

# Regular arrays approach
names_reg = np.array(['Person_' + str(i) for i in range(n)])
ages_reg = np.random.randint(18, 80, n)
salaries_reg = np.random.uniform(30000, 150000, n)

# Structured array approach
person_dtype = np.dtype([('name', 'U20'), ('age', 'i4'), ('salary', 'f8')])
people_structured = np.zeros(n, dtype=person_dtype)
people_structured['name'] = ['Person_' + str(i) for i in range(n)]
people_structured['age'] = np.random.randint(18, 80, n)
people_structured['salary'] = np.random.uniform(30000, 150000, n)

# Memory usage comparison
print("Memory usage comparison:")
print(f"Regular arrays: {names_reg.nbytes + ages_reg.nbytes + salaries_reg.nbytes:,} bytes")
print(f"Structured array: {people_structured.nbytes:,} bytes")
print(f"Memory efficiency: {((names_reg.nbytes + ages_reg.nbytes + salaries_reg.nbytes) / people_structured.nbytes):.2f}x")
print()

# Access time comparison
def time_operation(func, *args, iterations=100):
    start = time.time()
    for _ in range(iterations):
        func(*args)
    return (time.time() - start) / iterations

# Test access speed
def access_regular():
    return ages_reg[ages_reg > 50].mean()

def access_structured():
    return people_structured['age'][people_structured['age'] > 50].mean()

regular_time = time_operation(access_regular)
structured_time = time_operation(access_structured)

print("Access time comparison (100 iterations):")
print(f"Regular arrays: {regular_time:.6f} seconds")
print(f"Structured array: {structured_time:.6f} seconds")
print(f"Performance ratio: {regular_time/structured_time:.2f}x")
print()

print("Key takeaways:")
print("- Structured arrays use less memory due to better data packing")
print("- Access patterns may have different performance characteristics")
print("- Structured arrays provide better data organization and type safety")

=== Performance: Structured Arrays vs Regular Arrays ===
Memory usage comparison:
Regular arrays: 6,400,000 bytes
Structured array: 9,200,000 bytes
Memory efficiency: 0.70x

Access time comparison (100 iterations):
Regular arrays: 0.000657 seconds
Structured array: 0.000816 seconds
Performance ratio: 0.81x

Key takeaways:
- Structured arrays use less memory due to better data packing
- Access patterns may have different performance characteristics
- Structured arrays provide better data organization and type safety


### Structured Arrays Summary

**When to use structured arrays:**
- When you need database-like records with named fields
- When working with heterogeneous data types in a single array
- When memory efficiency and data organization are important
- When you need to perform operations on related fields together

**Advantages:**
- Memory efficient (better data packing)
- Type-safe field access
- Database-like operations
- Can handle complex nested structures

**Limitations:**
- Less flexible than pandas DataFrames for complex operations
- Field access syntax can be verbose
- Some NumPy operations may not work as expected

**Next:** Masked Arrays - Handling missing and invalid data

# Masked Arrays

Masked arrays in NumPy allow you to handle arrays with missing or invalid data. Unlike using NaN values, masked arrays explicitly mark certain elements as invalid, which can be more efficient and semantically clear.

## Creating Masked Arrays

You can create masked arrays using `numpy.ma` module:

In [7]:
import numpy as np
import numpy.ma as ma

# Create a regular array with some invalid data
data = np.array([1, 2, 3, -999, 5, 6, -999, 8])
print("Original data:", data)

# Create a masked array by masking invalid values (-999)
masked_data = ma.masked_values(data, -999)
print("Masked data:", masked_data)
print("Mask:", masked_data.mask)
print("Data without mask:", masked_data.data)

Original data: [   1    2    3 -999    5    6 -999    8]
Masked data: [1 2 3 -- 5 6 -- 8]
Mask: [False False False  True False False  True False]
Data without mask: [   1    2    3 -999    5    6 -999    8]


In [8]:
# Operations on masked arrays
print("\n--- Operations on Masked Arrays ---")

# Arithmetic operations automatically handle masks
result = masked_data * 2
print("Masked data * 2:", result)

# Statistical operations ignore masked values
print("Mean of masked data:", ma.mean(masked_data))
print("Sum of masked data:", ma.sum(masked_data))

# Comparison with masked arrays
high_values = ma.masked_less(masked_data, 5)
print("Values >= 5:", high_values)


--- Operations on Masked Arrays ---
Masked data * 2: [2 4 6 -- 10 12 -- 16]
Mean of masked data: 4.166666666666667
Sum of masked data: 25
Values >= 5: [-- -- -- -- 5 6 -- 8]


In [9]:
# Creating masks manually
print("\n--- Creating Masks Manually ---")

data2 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
mask = np.array([False, False, True, False, True, False, False, True])
masked_manual = ma.array(data2, mask=mask)
print("Data:", data2)
print("Manual mask:", mask)
print("Masked array:", masked_manual)

# Masking based on conditions
data3 = np.random.randn(10)
print("\nRandom data:", data3)
# Mask outliers (values beyond 2 standard deviations)
masked_outliers = ma.masked_outside(data3, -2, 2)
print("Masked outliers:", masked_outliers)


--- Creating Masks Manually ---
Data: [1 2 3 4 5 6 7 8]
Manual mask: [False False  True False  True False False  True]
Masked array: [1 2 -- 4 -- 6 7 --]

Random data: [-0.3805705  -0.0940733   2.72672067  1.088591    0.90486226  0.20329797
 -1.86974004 -1.2257099  -0.37720446 -0.38424072]
Masked outliers: [-0.3805704972480294 -0.09407329992593177 -- 1.0885910045201759
 0.904862258980352 0.20329797264222355 -1.8697400383884184
 -1.225709895856819 -0.3772044567143713 -0.3842407191175909]


In [10]:
# Performance benefits and use cases
print("\n--- Performance and Use Cases ---")

# Large dataset with missing values
large_data = np.random.randn(1000000)
# Introduce some NaN values
large_data[np.random.choice(len(large_data), 100000, replace=False)] = np.nan

# Using masked arrays vs NaN
masked_large = ma.masked_invalid(large_data)

import time

# Performance comparison
start = time.time()
nan_mean = np.nanmean(large_data)
nan_time = time.time() - start

start = time.time()
masked_mean = ma.mean(masked_large)
masked_time = time.time() - start

print(f"NaN mean: {nan_mean:.4f} (time: {nan_time:.4f}s)")
print(f"Masked mean: {masked_mean:.4f} (time: {masked_time:.4f}s)")
print(f"Masked arrays can be more predictable and memory efficient for certain operations")

# Filling masked values
filled_data = ma.filled(masked_large, -999)
print("\nFilled masked data (first 10):", filled_data[:10])


--- Performance and Use Cases ---
NaN mean: 0.0014 (time: 0.0096s)
Masked mean: 0.0014 (time: 0.0087s)
Masked arrays can be more predictable and memory efficient for certain operations

Filled masked data (first 10): [-0.47162355  0.37279022  0.90733894  1.21942285  0.01803367 -0.80163735
 -1.00383948 -0.93661558 -0.76166824 -1.44658448]


## Masked Arrays Summary

Masked arrays are powerful for:
- Handling missing or invalid data explicitly
- Performing operations that automatically ignore masked values
- Memory efficiency compared to using separate mask arrays
- Integration with NumPy's mathematical functions
- Data analysis workflows where missing data is common

Key functions:
- `ma.masked_values()`: Mask specific values
- `ma.masked_invalid()`: Mask NaN/inf values
- `ma.mean()`, `ma.sum()`: Statistics ignoring masks
- `ma.filled()`: Fill masked values with a default

Next: Universal Functions (ufuncs) and Broadcasting

# Universal Functions (ufuncs) and Broadcasting

Universal functions (ufuncs) are NumPy functions that operate element-wise on arrays. Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding smaller arrays to match larger ones.

## Universal Functions

Ufuncs are vectorized functions that apply operations to each element of an array:

In [11]:
import numpy as np

# Basic ufunc examples
print("--- Universal Functions (ufuncs) ---")

# Arithmetic ufuncs
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Array a:", a)
print("Array b:", b)
print("a + b:", a + b)  # np.add(a, b)
print("a * b:", a * b)  # np.multiply(a, b)
print("a ** b:", a ** b)  # np.power(a, b)

# Trigonometric ufuncs
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("\nAngles:", angles)
print("sin(angles):", np.sin(angles))
print("cos(angles):", np.cos(angles))

# Comparison ufuncs
print("\nComparison operations:")
print("a > 2:", a > 2)
print("a == b:", a == b)

# Aggregate ufuncs
print("\nAggregate functions:")
print("sum of a:", np.sum(a))
print("mean of a:", np.mean(a))
print("max of a:", np.max(a))
print("standard deviation of a:", np.std(a))

--- Universal Functions (ufuncs) ---
Array a: [1 2 3 4]
Array b: [5 6 7 8]
a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]
a ** b: [    1    64  2187 65536]

Angles: [0.         0.78539816 1.57079633 3.14159265]
sin(angles): [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(angles): [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]

Comparison operations:
a > 2: [False False  True  True]
a == b: [False False False False]

Aggregate functions:
sum of a: 10
mean of a: 2.5
max of a: 4
standard deviation of a: 1.118033988749895


## Broadcasting

Broadcasting allows operations between arrays of different shapes. NumPy automatically expands smaller arrays to match larger ones following these rules:

1. If arrays have different dimensions, pad the smaller shape with 1s on the left
2. If shapes don't match in any dimension, the dimension with size 1 is stretched
3. If sizes are incompatible (neither 1 nor equal), broadcasting fails

In [12]:
# Broadcasting examples
print("\n--- Broadcasting Examples ---")

# Example 1: Scalar broadcasting
matrix = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print("Matrix shape:", matrix.shape)
print("Scalar:", scalar)
print("Matrix + scalar:")
print(matrix + scalar)

# Example 2: 1D array broadcasting with 2D array
vector = np.array([1, 2, 3])
print("\nVector shape:", vector.shape)
print("Matrix shape:", matrix.shape)
print("Matrix + vector (broadcasting):")
print(matrix + vector)

# Example 3: Column-wise broadcasting
column_vector = np.array([[1], [2]])
small_matrix = np.array([[10, 20, 30], [40, 50, 60]])
print("\nColumn vector shape:", column_vector.shape)
print("Small matrix shape:", small_matrix.shape)
print("Small matrix + column vector:")
print(small_matrix + column_vector)


--- Broadcasting Examples ---
Matrix shape: (2, 3)
Scalar: 10
Matrix + scalar:
[[11 12 13]
 [14 15 16]]

Vector shape: (3,)
Matrix shape: (2, 3)
Matrix + vector (broadcasting):
[[2 4 6]
 [5 7 9]]

Column vector shape: (2, 1)
Small matrix shape: (2, 3)
Small matrix + column vector:
[[11 21 31]
 [42 52 62]]


In [13]:
# Advanced broadcasting examples
print("\n--- Advanced Broadcasting ---")

# Broadcasting rules demonstration
A = np.array([1, 2, 3])        # Shape: (3,)
B = np.array([[1], [2], [3]])  # Shape: (3, 1)
C = np.array([[1, 2, 3]])      # Shape: (1, 3)

print("A shape:", A.shape, "->", A)
print("B shape:", B.shape, "->", B.flatten())
print("C shape:", C.shape, "->", C.flatten())

print("\nA + B (broadcasting):")
print(A + B)
print("Shape of result:", (A + B).shape)

print("\nB + C (broadcasting):")
print(B + C)
print("Shape of result:", (B + C).shape)

# Broadcasting with different dimensions
D = np.array([[[1, 2]], [[3, 4]]])  # Shape: (2, 1, 2)
E = np.array([10, 20])               # Shape: (2,)

print("\nD shape:", D.shape)
print("E shape:", E.shape)
print("D + E (broadcasting):")
print(D + E)
print("Shape of result:", (D + E).shape)


--- Advanced Broadcasting ---
A shape: (3,) -> [1 2 3]
B shape: (3, 1) -> [1 2 3]
C shape: (1, 3) -> [1 2 3]

A + B (broadcasting):
[[2 3 4]
 [3 4 5]
 [4 5 6]]
Shape of result: (3, 3)

B + C (broadcasting):
[[2 3 4]
 [3 4 5]
 [4 5 6]]
Shape of result: (3, 3)

D shape: (2, 1, 2)
E shape: (2,)
D + E (broadcasting):
[[[11 22]]

 [[13 24]]]
Shape of result: (2, 1, 2)


In [14]:
# Performance comparison: ufuncs vs loops
print("\n--- Performance: ufuncs vs Python loops ---")

import time

# Large arrays for performance testing
size = 1000000
a_large = np.random.randn(size)
b_large = np.random.randn(size)

# Using ufuncs (vectorized)
start = time.time()
c_ufunc = a_large + b_large
ufunc_time = time.time() - start

# Using Python loop
c_loop = np.zeros(size)
start = time.time()
for i in range(size):
    c_loop[i] = a_large[i] + b_large[i]
loop_time = time.time() - start

print(f"Array size: {size}")
print(f"Ufunc time: {ufunc_time:.4f} seconds")
print(f"Loop time: {loop_time:.4f} seconds")
print(f"Speedup: {loop_time/ufunc_time:.1f}x faster")

# Broadcasting performance
matrix_large = np.random.randn(1000, 1000)
vector = np.random.randn(1000)

start = time.time()
result_broadcast = matrix_large + vector
broadcast_time = time.time() - start

print(f"\nBroadcasting example (1000x1000 matrix + vector):")
print(f"Time: {broadcast_time:.4f} seconds")
print("Broadcasting automatically handles the operation without explicit loops!")


--- Performance: ufuncs vs Python loops ---
Array size: 1000000
Ufunc time: 0.0040 seconds
Loop time: 0.3841 seconds
Speedup: 96.8x faster

Broadcasting example (1000x1000 matrix + vector):
Time: 0.0041 seconds
Broadcasting automatically handles the operation without explicit loops!


## Universal Functions and Broadcasting Summary

**Universal Functions (ufuncs):**
- Element-wise operations on arrays
- Include arithmetic, trigonometric, comparison, and aggregate functions
- Much faster than Python loops due to vectorization
- Examples: `np.add()`, `np.sin()`, `np.sum()`, `np.mean()`

**Broadcasting Rules:**
1. Pad shapes with 1s on the left to match dimensions
2. Stretch dimensions of size 1 to match other dimensions
3. Fail if dimensions are incompatible

**Key Benefits:**
- Eliminates explicit loops for better performance
- Simplifies code by handling shape mismatches automatically
- Enables operations between arrays of different shapes
- Fundamental to NumPy's efficiency

**Common Broadcasting Patterns:**
- Scalar + array: scalar broadcasted to all elements
- Vector + matrix: vector broadcasted across rows/columns
- Different dimensional operations with compatible shapes

Next: Advanced Array Manipulation and Memory Layout

# Advanced Array Manipulation and Memory Layout

NumPy provides powerful tools for manipulating array shapes, understanding memory layout, and optimizing performance through efficient data access patterns.

## Array Reshaping and Views

Reshaping arrays without copying data creates views that share memory with the original array:

In [15]:
import numpy as np

# Array reshaping and views
print("--- Array Reshaping and Views ---")

# Create a 1D array
original = np.arange(12)
print("Original array:", original)
print("Original shape:", original.shape)

# Reshape to different dimensions
reshaped_2d = original.reshape(3, 4)
print("\nReshaped to (3, 4):")
print(reshaped_2d)

reshaped_3d = original.reshape(2, 2, 3)
print("\nReshaped to (2, 2, 3):")
print(reshaped_3d)

# Views vs copies
print("\n--- Views vs Copies ---")

# Create a view (shares memory)
view = original.reshape(3, 4)
print("Original array:", original)
print("View of original:", view)

# Modify the view
view[0, 0] = 999
print("After modifying view[0, 0] = 999:")
print("Original array:", original)
print("View:", view)

# Create a copy (independent memory)
copy_array = original.copy().reshape(3, 4)
copy_array[0, 0] = 888
print("\nAfter modifying copy[0, 0] = 888:")
print("Original array:", original)
print("Copy:", copy_array)

--- Array Reshaping and Views ---
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original shape: (12,)

Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 2, 3):
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

--- Views vs Copies ---
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
View of original: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After modifying view[0, 0] = 999:
Original array: [999   1   2   3   4   5   6   7   8   9  10  11]
View: [[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

After modifying copy[0, 0] = 888:
Original array: [999   1   2   3   4   5   6   7   8   9  10  11]
Copy: [[888   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


## Memory Layout: C-Order vs F-Order

NumPy arrays can be stored in memory in different orders:
- **C-order (row-major)**: Last dimension varies fastest (default in NumPy)
- **F-order (column-major)**: First dimension varies fastest (Fortran/MATLAB style)

Memory layout affects performance when accessing elements in different patterns:

In [16]:
# Memory layout examples
print("\n--- Memory Layout: C-Order vs F-Order ---")

# Create arrays with different memory layouts
c_order = np.arange(6).reshape(2, 3)
f_order = np.arange(6).reshape(2, 3, order='F')

print("C-order array (default):")
print(c_order)
print("Memory layout (flattened):", c_order.flatten())

print("\nF-order array:")
print(f_order)
print("Memory layout (flattened):", f_order.flatten())

# Check memory layout
print("\nArray flags:")
print("C-order contiguous:", c_order.flags.c_contiguous)
print("F-order contiguous:", f_order.flags.f_contiguous)

# Performance implications
import time

# Large arrays for performance testing
size = 1000
c_array = np.random.randn(size, size)
f_array = np.asfortranarray(np.random.randn(size, size))

# Row-wise access (fast for C-order, slow for F-order)
start = time.time()
row_sum_c = np.sum(c_array, axis=1)
row_time_c = time.time() - start

start = time.time()
row_sum_f = np.sum(f_array, axis=1)
row_time_f = time.time() - start

# Column-wise access (fast for F-order, slow for C-order)
start = time.time()
col_sum_c = np.sum(c_array, axis=0)
col_time_c = time.time() - start

start = time.time()
col_sum_f = np.sum(f_array, axis=0)
col_time_f = time.time() - start

print(f"\nPerformance comparison ({size}x{size} array):")
print(f"Row access - C-order: {row_time_c:.4f}s, F-order: {row_time_f:.4f}s")
print(f"Col access - C-order: {col_time_c:.4f}s, F-order: {col_time_f:.4f}s")
print(f"Row access speedup (C-order): {row_time_f/row_time_c:.1f}x")
print(f"Col access speedup (F-order): {col_time_c/col_time_f:.1f}x")


--- Memory Layout: C-Order vs F-Order ---
C-order array (default):
[[0 1 2]
 [3 4 5]]
Memory layout (flattened): [0 1 2 3 4 5]

F-order array:
[[0 2 4]
 [1 3 5]]
Memory layout (flattened): [0 2 4 1 3 5]

Array flags:
C-order contiguous: True
F-order contiguous: True

Performance comparison (1000x1000 array):
Row access - C-order: 0.0007s, F-order: 0.0006s
Col access - C-order: 0.0006s, F-order: 0.0006s
Row access speedup (C-order): 0.8x
Col access speedup (F-order): 1.1x


## Advanced Indexing and Array Operations

NumPy supports sophisticated indexing techniques and array combination operations:

In [18]:
# Advanced indexing and array operations
print("\n--- Advanced Indexing ---")

# Create a sample array
arr = np.arange(24).reshape(4, 6)
print("Original array:")
print(arr)

# Boolean indexing
mask = arr > 10
print("\nBoolean mask (arr > 10):")
print(mask)
print("Elements > 10:", arr[mask])

# Fancy indexing
rows = np.array([0, 2, 3])
cols = np.array([1, 3, 5])
print("\nFancy indexing with arrays:")
print("Rows:", rows)
print("Cols:", cols)
print("arr[rows, cols]:", arr[rows, cols])

# Combined indexing
print("\nCombined boolean and fancy indexing:")
# This creates an error - boolean indexing with fancy indexing doesn't work this way
# Instead, use boolean indexing first, then fancy indexing
filtered_rows = arr[arr[:, 0] > 15]  # Filter rows where first column > 15
print("Rows where first column > 15:")
print(filtered_rows)
print("Then select specific columns from filtered rows:")
print(filtered_rows[:, [0, 2, 4]])

# Array concatenation and stacking
print("\n--- Array Concatenation and Stacking ---")

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Array a:")
print(a)
print("Array b:")
print(b)

# Concatenate along different axes
print("\nConcatenate along axis 0 (rows):")
print(np.concatenate([a, b], axis=0))

print("\nConcatenate along axis 1 (columns):")
print(np.concatenate([a, b], axis=1))

# Stacking
print("\nStack along new axis (depth):")
print(np.stack([a, b], axis=0))

print("\nHorizontal stack:")
print(np.hstack([a, b]))

print("\nVertical stack:")
print(np.vstack([a, b]))


--- Advanced Indexing ---
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Boolean mask (arr > 10):
[[False False False False False False]
 [False False False False False  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
Elements > 10: [11 12 13 14 15 16 17 18 19 20 21 22 23]

Fancy indexing with arrays:
Rows: [0 2 3]
Cols: [1 3 5]
arr[rows, cols]: [ 1 15 23]

Combined boolean and fancy indexing:
Rows where first column > 15:
[[18 19 20 21 22 23]]
Then select specific columns from filtered rows:
[[18 20 22]]

--- Array Concatenation and Stacking ---
Array a:
[[1 2]
 [3 4]]
Array b:
[[5 6]
 [7 8]]

Concatenate along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]

Stack along new axis (depth):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]

Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Memory Efficiency and Optimization

Understanding when NumPy creates views vs copies is crucial for memory efficiency:

In [19]:
# Memory efficiency examples
print("\n--- Memory Efficiency ---")

# Check if arrays share memory
original = np.arange(12)
view = original.reshape(3, 4)
copy = original.copy()

print("Original array:", original)
print("View shares memory with original:", np.shares_memory(original, view))
print("Copy shares memory with original:", np.shares_memory(original, copy))

# Slicing creates views (usually)
sliced = original[::2]
print("\nSliced array:", sliced)
print("Slice shares memory:", np.shares_memory(original, sliced))

# But fancy indexing creates copies
fancy = original[[0, 2, 4, 6]]
print("Fancy indexed array:", fancy)
print("Fancy indexing shares memory:", np.shares_memory(original, fancy))

# In-place operations vs creating new arrays
print("\n--- In-place Operations ---")

a = np.arange(5)
print("Original a:", a)

# Creates new array
b = a + 1
print("a + 1 (new array):", b)
print("a is b:", a is b)

# In-place operation
a += 1
print("a += 1 (in-place):", a)

# Memory usage comparison
import sys

large_array = np.random.randn(10000, 10000)
print(f"\nLarge array memory usage: {large_array.nbytes / 1024**2:.1f} MB")

# Views use no extra memory
view_of_large = large_array[::2, ::2]
print(f"View memory usage: {view_of_large.nbytes / 1024**2:.1f} MB")
print("View shares memory:", np.shares_memory(large_array, view_of_large))

# Copies use full memory
copy_of_large = large_array.copy()
print(f"Copy memory usage: {copy_of_large.nbytes / 1024**2:.1f} MB")
print("Copy shares memory:", np.shares_memory(large_array, copy_of_large))


--- Memory Efficiency ---
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
View shares memory with original: True
Copy shares memory with original: False

Sliced array: [ 0  2  4  6  8 10]
Slice shares memory: True
Fancy indexed array: [0 2 4 6]
Fancy indexing shares memory: False

--- In-place Operations ---
Original a: [0 1 2 3 4]
a + 1 (new array): [1 2 3 4 5]
a is b: False
a += 1 (in-place): [1 2 3 4 5]

Large array memory usage: 762.9 MB
View memory usage: 190.7 MB
View shares memory: True
Copy memory usage: 762.9 MB
Copy shares memory: False


## Advanced Array Manipulation Summary

**Array Reshaping:**
- `reshape()`: Change shape without copying (creates views)
- `flatten()` vs `ravel()`: `ravel()` may return a view
- Views share memory, copies are independent

**Memory Layout:**
- C-order (row-major): Default, fast row-wise access
- F-order (column-major): Fast column-wise access
- Choose layout based on access patterns for optimal performance

**Advanced Indexing:**
- Boolean indexing: `arr[condition]`
- Fancy indexing: `arr[row_indices, col_indices]`
- Combined indexing: Mix boolean and fancy indexing

**Array Operations:**
- `concatenate()`: Join arrays along existing axis
- `stack()`: Join arrays along new axis
- `hstack()`/`vstack()`: Horizontal/vertical stacking

**Memory Efficiency:**
- Views (`reshape`, slicing) share memory, use no extra space
- Copies (`copy()`, fancy indexing) duplicate data
- Use `np.shares_memory()` to check memory sharing
- In-place operations (`+=`, `*=`) modify arrays without copying

**Performance Tips:**
- Prefer views over copies when possible
- Choose memory layout based on access patterns
- Use in-place operations to avoid temporary arrays
- Vectorize operations instead of loops

Next: NumPy's Random Module and Statistical Functions

# NumPy's Random Module and Statistical Functions

NumPy provides comprehensive random number generation and statistical analysis capabilities essential for data science, simulations, and statistical computing.

## Random Number Generation

NumPy's random module offers various probability distributions and random sampling methods:

In [20]:
import numpy as np

# Set seed for reproducible results
np.random.seed(42)

print("--- Random Number Generation ---")

# Uniform random numbers
print("Uniform random [0, 1):", np.random.random(5))
print("Uniform random integers [1, 10):", np.random.randint(1, 10, 5))

# Normal distribution
print("\nNormal distribution (mean=0, std=1):", np.random.randn(5))
print("Normal with custom parameters (mean=5, std=2):", np.random.normal(5, 2, 5))

# Other distributions
print("\nExponential distribution:", np.random.exponential(1.0, 5))
print("Poisson distribution (λ=3):", np.random.poisson(3, 5))
print("Beta distribution (α=2, β=5):", np.random.beta(2, 5, 5))

# Random sampling
population = np.arange(10)
print("\nPopulation:", population)
print("Random sample (with replacement):", np.random.choice(population, 5, replace=True))
print("Random sample (without replacement):", np.random.choice(population, 5, replace=False))

# Shuffling
arr = np.arange(10)
print("\nOriginal array:", arr)
np.random.shuffle(arr)
print("Shuffled array:", arr)

# Permutations
original = np.arange(5)
print("\nOriginal:", original)
print("Random permutation:", np.random.permutation(original))
print("Original unchanged:", original)

--- Random Number Generation ---
Uniform random [0, 1): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Uniform random integers [1, 10): [3 7 8 5 4]

Normal distribution (mean=0, std=1): [ 0.39257975 -0.92918467  0.07983181 -0.1595165   0.02222183]
Normal with custom parameters (mean=5, std=2): [4.14441417 3.93636518 4.765049   5.4441578  3.464047  ]

Exponential distribution: [0.48201466 4.08821653 0.6287891  1.96568728 1.1403958 ]
Poisson distribution (λ=3): [1 3 2 3 3]
Beta distribution (α=2, β=5): [0.19140266 0.38894996 0.18153023 0.18100093 0.05580134]

Population: [0 1 2 3 4 5 6 7 8 9]
Random sample (with replacement): [8 6 8 7 0]
Random sample (without replacement): [1 4 5 3 0]

Original array: [0 1 2 3 4 5 6 7 8 9]
Shuffled array: [5 8 2 3 9 7 6 1 4 0]

Original: [0 1 2 3 4]
Random permutation: [2 4 0 1 3]
Original unchanged: [0 1 2 3 4]


## Statistical Functions

NumPy provides comprehensive statistical analysis functions for arrays:

In [23]:
# Statistical functions
print("\n--- Statistical Functions ---")

# Generate sample data
np.random.seed(42)
data = np.random.normal(10, 3, 1000)  # Normal distribution: mean=10, std=3

print("Sample data statistics:")
print(f"Mean: {np.mean(data):.3f}")
print(f"Median: {np.median(data):.3f}")
print(f"Standard deviation: {np.std(data):.3f}")
print(f"Variance: {np.var(data):.3f}")
print(f"Minimum: {np.min(data):.3f}")
print(f"Maximum: {np.max(data):.3f}")

# Percentiles and quantiles
print(f"\n25th percentile: {np.percentile(data, 25):.3f}")
print(f"75th percentile: {np.percentile(data, 75):.3f}")
print(f"Interquartile range: {np.percentile(data, 75) - np.percentile(data, 25):.3f}")

# Multi-dimensional statistics
matrix = np.random.randn(50, 4)
print("\nMatrix statistics (50x4):")
print("Mean along columns:", np.mean(matrix, axis=0))
print("Std along rows:", np.std(matrix, axis=1))

# Correlation and covariance
x = np.random.randn(100)
y = 2*x + np.random.randn(100) * 0.5  # Correlated with x

print("\nCorrelation and covariance:")
print(f"Pearson correlation: {np.corrcoef(x, y)[0, 1]:.3f}")
cov_matrix = np.cov(x, y)
print("Covariance matrix:")
print(cov_matrix)


--- Statistical Functions ---
Sample data statistics:
Mean: 10.058
Median: 10.076
Standard deviation: 2.936
Variance: 8.621
Minimum: 0.276
Maximum: 21.558

25th percentile: 8.057
75th percentile: 11.944
Interquartile range: 3.887

Matrix statistics (50x4):
Mean along columns: [ 0.31572179  0.01241903  0.22843039 -0.02203915]
Std along rows: [0.78759275 0.17912497 0.73025413 1.12682224 0.41080398 1.01540988
 0.67875414 0.85287654 0.73266952 1.03568685 0.85563161 0.96304806
 0.85259865 0.5028309  0.58589597 1.67904006 0.96900812 0.36902591
 0.8313437  1.17769326 1.04647634 0.30274692 0.09025457 0.37520744
 1.10123456 1.85502527 0.96953414 0.96210834 0.26166711 0.96026689
 0.94156483 1.07731292 0.18676148 0.68131239 0.91831594 0.65989532
 0.61065484 1.36409762 1.19956593 1.16005849 1.83737101 0.69171098
 0.21748298 0.32229214 0.57022958 1.12564893 0.78831877 0.76695364
 0.81874698 0.52251462]

Correlation and covariance:
Pearson correlation: 0.971
Covariance matrix:
[[1.00154325 1.993534

## Histograms and Distribution Analysis

NumPy provides tools for analyzing data distributions and creating histograms:

In [25]:
# Histograms and distribution analysis
print("\n--- Histograms and Distribution Analysis ---")

# Generate data from different distributions
np.random.seed(42)
normal_data = np.random.normal(0, 1, 10000)
uniform_data = np.random.uniform(-2, 2, 10000)
exponential_data = np.random.exponential(1, 10000)

# Create histograms
hist_normal, bins_normal = np.histogram(normal_data, bins=50)
hist_uniform, bins_uniform = np.histogram(uniform_data, bins=50)
hist_exp, bins_exp = np.histogram(exponential_data, bins=50)

print("Normal distribution histogram (first 10 bins):")
print("Bin edges:", bins_normal[:11])
print("Counts:", hist_normal[:10])

print("\nUniform distribution histogram (first 10 bins):")
print("Bin edges:", bins_uniform[:11])
print("Counts:", hist_uniform[:10])

# Statistical tests and distribution properties
from scipy import stats  # Note: scipy is often used with numpy for advanced stats

print("\nDistribution properties:")
print(f"Normal data - skewness: {stats.skew(normal_data):.3f}, kurtosis: {stats.kurtosis(normal_data):.3f}")
print(f"Uniform data - skewness: {stats.skew(uniform_data):.3f}, kurtosis: {stats.kurtosis(uniform_data):.3f}")
print(f"Exponential data - skewness: {stats.skew(exponential_data):.3f}, kurtosis: {stats.kurtosis(exponential_data):.3f}")

# Binning and digitization
data = np.random.randn(100)
bins = np.linspace(-3, 3, 7)  # 6 bins from -3 to 3
digitized = np.digitize(data, bins)

print("\nBinning example:")
print("Bins:", bins)
print("Sample data (first 10):", data[:10])
print("Digitized (first 10):", digitized[:10])
print("Unique bin counts:", np.bincount(digitized))

# Cumulative distributions
sorted_data = np.sort(normal_data)
yvals = np.arange(len(sorted_data)) / float(len(sorted_data))

print("\nEmpirical CDF (first 10 points):")
for i in range(10):
    print(f"Value: {sorted_data[i]:.3f}, CDF: {yvals[i]:.3f}")


--- Histograms and Distribution Analysis ---
Normal distribution histogram (first 10 bins):
Bin edges: [-3.92240025 -3.76542749 -3.60845473 -3.45148197 -3.29450921 -3.13753646
 -2.9805637  -2.82359094 -2.66661818 -2.50964542 -2.35267266]
Counts: [ 2  1  1  0  6  4 18 12 20 34]

Uniform distribution histogram (first 10 bins):
Bin edges: [-1.9998075  -1.91981737 -1.83982723 -1.7598371  -1.67984696 -1.59985682
 -1.51986669 -1.43987655 -1.35988641 -1.27989628 -1.19990614]
Counts: [197 194 212 220 191 183 166 187 194 208]

Distribution properties:
Normal data - skewness: 0.002, kurtosis: 0.026
Uniform data - skewness: -0.034, kurtosis: -1.193
Exponential data - skewness: 2.004, kurtosis: 5.697

Binning example:
Bins: [-3. -2. -1.  0.  1.  2.  3.]
Sample data (first 10): [ 0.59910163 -1.23215802  0.11161086 -0.928763   -1.38894052  0.41095333
  1.15814956 -0.38336882 -0.21201289 -1.13815065]
Digitized (first 10): [4 2 4 3 2 4 5 3 3 2]
Unique bin counts: [ 0  1 20 27 36 14  2]

Empirical CDF

## Random Seeds and Reproducibility

Controlling random number generation is crucial for reproducible results in scientific computing:

In [26]:
# Random seeds and reproducibility
print("\n--- Random Seeds and Reproducibility ---")

# Demonstrate reproducibility with seeds
print("Without seed (different each time):")
print("Run 1:", np.random.randint(0, 100, 3))
print("Run 2:", np.random.randint(0, 100, 3))

print("\nWith seed (reproducible):")
np.random.seed(123)
print("Run 1:", np.random.randint(0, 100, 3))

np.random.seed(123)  # Reset seed
print("Run 2 (same as Run 1):", np.random.randint(0, 100, 3))

# Random state objects for more control
rng1 = np.random.RandomState(42)
rng2 = np.random.RandomState(42)

print("\nUsing RandomState objects:")
print("RNG1:", rng1.randn(3))
print("RNG2 (same seed):", rng2.randn(3))

# Reset and get same sequence
rng1 = np.random.RandomState(42)
rng2 = np.random.RandomState(42)
print("RNG1 reset:", rng1.randn(3))
print("RNG2 reset (same):", rng2.randn(3))

# Different sequences with different seeds
rng_a = np.random.RandomState(1)
rng_b = np.random.RandomState(2)
print("\nDifferent seeds:")
print("Seed 1:", rng_a.randn(3))
print("Seed 2:", rng_b.randn(3))

# Global seed vs local RandomState
print("\nGlobal seed vs RandomState:")
np.random.seed(99)
print("Global seed:", np.random.randn(2))

local_rng = np.random.RandomState(99)
print("Local RandomState:", local_rng.randn(2))


--- Random Seeds and Reproducibility ---
Without seed (different each time):
Run 1: [97 41 37]
Run 2: [15 73 46]

With seed (reproducible):
Run 1: [66 92 98]
Run 2 (same as Run 1): [66 92 98]

Using RandomState objects:
RNG1: [ 0.49671415 -0.1382643   0.64768854]
RNG2 (same seed): [ 0.49671415 -0.1382643   0.64768854]
RNG1 reset: [ 0.49671415 -0.1382643   0.64768854]
RNG2 reset (same): [ 0.49671415 -0.1382643   0.64768854]

Different seeds:
Seed 1: [ 1.62434536 -0.61175641 -0.52817175]
Seed 2: [-0.41675785 -0.05626683 -2.1361961 ]

Global seed vs RandomState:
Global seed: [-0.14235884  2.05722174]
Local RandomState: [-0.14235884  2.05722174]


## NumPy Random and Statistics Summary

**Random Number Generation:**
- `np.random.random()`: Uniform [0, 1)
- `np.random.randn()`: Standard normal distribution
- `np.random.randint(a, b)`: Random integers
- `np.random.choice()`: Random sampling with/without replacement
- `np.random.shuffle()`: In-place shuffling
- `np.random.permutation()`: Return shuffled copy

**Statistical Functions:**
- Central tendency: `mean()`, `median()`
- Spread: `std()`, `var()`, `percentile()`
- Multi-dimensional: `axis` parameter for row/column operations
- Correlation: `corrcoef()`, covariance: `cov()`

**Distribution Analysis:**
- `np.histogram()`: Create histograms and bin data
- `np.digitize()`: Bin continuous data into discrete categories
- Empirical CDFs for distribution analysis
- Integration with scipy.stats for advanced statistical tests

**Reproducibility:**
- `np.random.seed()`: Set global random seed
- `np.random.RandomState()`: Create independent random number generators
- Essential for scientific computing and debugging
- Different seeds produce different sequences

**Key Applications:**
- Monte Carlo simulations
- Statistical sampling and bootstrapping
- Data augmentation for machine learning
- A/B testing and experimental design
- Financial modeling and risk analysis

Next: Linear Algebra with NumPy

# Linear Algebra with NumPy

NumPy provides comprehensive linear algebra functionality through the `numpy.linalg` module, essential for scientific computing, machine learning, and data analysis.

## Basic Matrix Operations

Linear algebra operations form the foundation of many computational algorithms:

In [28]:
import numpy as np

print("--- Basic Matrix Operations ---")

# Create matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Matrix multiplication
print("\nMatrix multiplication A @ B:")
print(A @ B)

print("\nMatrix multiplication using np.dot:")
print(np.dot(A, B))

# Transpose
print("\nTranspose of A:")
print(A.T)

# Trace (sum of diagonal elements)
print(f"\nTrace of A: {np.trace(A)}")

# Determinant
print(f"Determinant of A: {np.linalg.det(A):.3f}")

# Matrix inverse
A_square = np.array([[4, 2], [3, 1]])
print("\nSquare matrix for inverse:")
print(A_square)
print("Inverse:")
print(np.linalg.inv(A_square))

# Verify inverse
print("A @ A^(-1):")
print(A_square @ np.linalg.inv(A_square))

--- Basic Matrix Operations ---
Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix multiplication A @ B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix multiplication using np.dot:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Transpose of A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Trace of A: 15
Determinant of A: -0.000

Square matrix for inverse:
[[4 2]
 [3 1]]
Inverse:
[[-0.5  1. ]
 [ 1.5 -2. ]]
A @ A^(-1):
[[1. 0.]
 [0. 1.]]


## Eigenvalues and Eigenvectors

Eigenvalues and eigenvectors are fundamental concepts in linear algebra with applications in data analysis, physics, and machine learning:

In [30]:
print("\n--- Eigenvalues and Eigenvectors ---")

# Symmetric matrix for clean eigenvalues
A_sym = np.array([[4, 2, 0],
                  [2, 3, 1],
                  [0, 1, 1]])

print("Matrix A:")
print(A_sym)

# Compute eigenvalues and eigenvectors
eigenvals, eigenvecs = np.linalg.eig(A_sym)

print(f"\nEigenvalues: {eigenvals}")
print("Eigenvectors:")
print(eigenvecs)

# Verify: A * v = λ * v
print("\nVerification (A * v1 should equal λ1 * v1):")
lambda1, v1 = eigenvals[0], eigenvecs[:, 0]
print(f"A * v1 = {A_sym @ v1}")
print(f"λ1 * v1 = {lambda1 * v1}")
print(f"Difference: {A_sym @ v1 - lambda1 * v1}")

# Eigenvalue decomposition: A = Q * Λ * Q^(-1)
# For symmetric matrices, Q is orthogonal (Q^(-1) = Q^T)
Q = eigenvecs
Lambda = np.diag(eigenvals)
A_reconstructed = Q @ Lambda @ Q.T

print("\nReconstructed matrix A:")
print(A_reconstructed)
print("Original matrix A:")
print(A_sym)
print(f"Reconstruction error: {np.max(np.abs(A_sym - A_reconstructed)):.2e}")

# Complex eigenvalues example
A_complex = np.array([[0, -1], [1, 0]])  # Rotation matrix
eigenvals_complex, eigenvecs_complex = np.linalg.eig(A_complex)

print("\nComplex eigenvalues example:")
print("Matrix (90-degree rotation):")
print(A_complex)
print(f"Eigenvalues: {eigenvals_complex}")
print("Eigenvectors:")
print(eigenvecs_complex)


--- Eigenvalues and Eigenvectors ---
Matrix A:
[[4 2 0]
 [2 3 1]
 [0 1 1]]

Eigenvalues: [5.64575131 2.         0.35424869]
Eigenvectors:
[[-0.76505532  0.57735027  0.28523152]
 [-0.6295454  -0.57735027 -0.51994159]
 [-0.13550992 -0.57735027  0.8051731 ]]

Verification (A * v1 should equal λ1 * v1):
A * v1 = [-4.3193121  -3.55425677 -0.76505532]
λ1 * v1 = [-4.3193121  -3.55425677 -0.76505532]
Difference: [-8.8817842e-16 -4.4408921e-16 -4.4408921e-16]

Reconstructed matrix A:
[[ 4.00000000e+00  2.00000000e+00 -1.87158839e-16]
 [ 2.00000000e+00  3.00000000e+00  1.00000000e+00]
 [-1.81666005e-16  1.00000000e+00  1.00000000e+00]]
Original matrix A:
[[4 2 0]
 [2 3 1]
 [0 1 1]]
Reconstruction error: 8.88e-16

Complex eigenvalues example:
Matrix (90-degree rotation):
[[ 0 -1]
 [ 1  0]]
Eigenvalues: [0.+1.j 0.-1.j]
Eigenvectors:
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


## Solving Linear Systems

Solving systems of linear equations is a fundamental operation with applications in optimization, physics, and data fitting:

In [32]:
print("\n--- Solving Linear Systems ---")

# System: A * x = b
# Example: 2x + 3y = 8
#          4x + y = 6

A = np.array([[2, 3], [4, 1]])
b = np.array([8, 6])

print("Coefficient matrix A:")
print(A)
print(f"Right-hand side b: {b}")

# Solve using np.linalg.solve (recommended for square systems)
x = np.linalg.solve(A, b)
print(f"\nSolution x: {x}")

# Verify solution
print(f"A @ x = {A @ x}")
print(f"Original b: {b}")
print(f"Difference: {A @ x - b}")

# Alternative: using inverse (less efficient, less stable)
x_inverse = np.linalg.inv(A) @ b
print(f"\nSolution using inverse: {x_inverse}")
print(f"Same result: {np.allclose(x, x_inverse)}")

# Overdetermined system (more equations than variables)
print("\n--- Overdetermined System ---")
A_over = np.array([[1, 1], [1, 2], [1, 3], [1, 4]])
b_over = np.array([6, 8, 10, 12])

print("Overdetermined system A:")
print(A_over)
print(f"b: {b_over}")

# Least squares solution
x_lstsq, residuals, rank, s = np.linalg.lstsq(A_over, b_over, rcond=None)
print(f"Least squares solution: {x_lstsq}")
print(f"Residuals: {residuals}")
print(f"Rank: {rank}")

# Verify
print(f"A @ x ≈ b: {np.allclose(A_over @ x_lstsq, b_over, atol=1e-10)}")

# Underdetermined system (fewer equations than variables)
print("\n--- Underdetermined System ---")
A_under = np.array([[1, 2, 3], [4, 5, 6]])
b_under = np.array([6, 15])

print("Underdetermined system A:")
print(A_under)
print(f"b: {b_under}")

# Find minimum norm solution
x_min_norm = np.linalg.pinv(A_under) @ b_under
print(f"Minimum norm solution: {x_min_norm}")
print(f"A @ x: {A_under @ x_min_norm}")
print(f"Original b: {b_under}")


--- Solving Linear Systems ---
Coefficient matrix A:
[[2 3]
 [4 1]]
Right-hand side b: [8 6]

Solution x: [1. 2.]
A @ x = [8. 6.]
Original b: [8 6]
Difference: [0. 0.]

Solution using inverse: [1. 2.]
Same result: True

--- Overdetermined System ---
Overdetermined system A:
[[1 1]
 [1 2]
 [1 3]
 [1 4]]
b: [ 6  8 10 12]
Least squares solution: [4. 2.]
Residuals: [6.28701299e-31]
Rank: 2
A @ x ≈ b: True

--- Underdetermined System ---
Underdetermined system A:
[[1 2 3]
 [4 5 6]]
b: [ 6 15]
Minimum norm solution: [1. 1. 1.]
A @ x: [ 6. 15.]
Original b: [ 6 15]


## Matrix Decompositions

Matrix decompositions break down matrices into simpler components, enabling efficient computations and insights into matrix properties:

In [34]:
print("\n--- Matrix Decompositions ---")

# Singular Value Decomposition (SVD)
print("Singular Value Decomposition (SVD):")
A_svd = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix A:")
print(A_svd)

U, s, Vt = np.linalg.svd(A_svd)
print(f"\nSingular values: {s}")
print("U matrix shape:", U.shape)
print("V^T matrix shape:", Vt.shape)

# Reconstruct matrix
Sigma = np.zeros(A_svd.shape)
np.fill_diagonal(Sigma, s)
A_reconstructed = U @ Sigma @ Vt
print("\nReconstructed matrix:")
print(A_reconstructed)
print("Original matrix:")
print(A_svd)
print(f"Reconstruction error: {np.max(np.abs(A_svd - A_reconstructed)):.2e}")

# QR Decomposition
print("\nQR Decomposition:")
A_qr = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=float)
print("Matrix A:")
print(A_qr)

Q, R = np.linalg.qr(A_qr)
print("\nQ matrix (orthogonal):")
print(Q)
print("R matrix (upper triangular):")
print(R)

# Verify: A = Q * R
A_qr_reconstructed = Q @ R
print("\nReconstructed A:")
print(A_qr_reconstructed)
print("Original A:")
print(A_qr)
print(f"Reconstruction error: {np.max(np.abs(A_qr - A_qr_reconstructed)):.2e}")

# Check if Q is orthogonal (Q^T * Q = I)
print("\nQ^T @ Q (should be identity):")
print(Q.T @ Q)
print(f"Is Q orthogonal? {np.allclose(Q.T @ Q, np.eye(3))}")

# Cholesky Decomposition (for positive definite matrices)
print("\nCholesky Decomposition (for symmetric positive definite matrices):")
A_pos_def = np.array([[4, 2, 0], [2, 3, 1], [0, 1, 1]])
print("Positive definite matrix A:")
print(A_pos_def)

L = np.linalg.cholesky(A_pos_def)
print("\nLower triangular L:")
print(L)

# Verify: A = L * L^T
A_chol_reconstructed = L @ L.T
print("\nReconstructed A:")
print(A_chol_reconstructed)
print("Original A:")
print(A_pos_def)
print(f"Reconstruction error: {np.max(np.abs(A_pos_def - A_chol_reconstructed)):.2e}")


--- Matrix Decompositions ---
Singular Value Decomposition (SVD):
Matrix A:
[[1 2 3]
 [4 5 6]]

Singular values: [9.508032   0.77286964]
U matrix shape: (2, 2)
V^T matrix shape: (3, 3)

Reconstructed matrix:
[[1. 2. 3.]
 [4. 5. 6.]]
Original matrix:
[[1 2 3]
 [4 5 6]]
Reconstruction error: 1.78e-15

QR Decomposition:
Matrix A:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]

Q matrix (orthogonal):
[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]
R matrix (upper triangular):
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]

Reconstructed A:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
Original A:
[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
Reconstruction error: 2.84e-14

Q^T @ Q (should be identity):
[[ 1.00000000e+00  0.00000000e+00 -8.15320034e-17]
 [ 0.00000000e+00  1.00000000e+00  1.04083409e-17]
 [-8.15320034e-17  1.04083409e-17  1.00000000e+00]]
Is Q orthogonal? True

C

## Norms and Condition Numbers

Matrix norms measure the "size" of matrices, while condition numbers indicate numerical stability of linear systems:

In [36]:
print("\n--- Norms and Condition Numbers ---")

# Vector norms
v = np.array([3, 4])
print("Vector v:", v)
print(f"L2 norm (Euclidean): {np.linalg.norm(v, 2):.3f}")
print(f"L1 norm (Manhattan): {np.linalg.norm(v, 1):.3f}")
print(f"L∞ norm (Chebyshev): {np.linalg.norm(v, np.inf):.3f}")

# Matrix norms
A = np.array([[1, 2], [3, 4]])
print("\nMatrix A:")
print(A)
print(f"Frobenius norm: {np.linalg.norm(A, 'fro'):.3f}")
print(f"Spectral norm (L2): {np.linalg.norm(A, 2):.3f}")
print(f"L1 norm: {np.linalg.norm(A, 1):.3f}")
print(f"L∞ norm: {np.linalg.norm(A, np.inf):.3f}")

# Condition numbers
print("\nCondition Numbers:")
# Well-conditioned matrix
A_well = np.array([[1, 0], [0, 1]])
cond_well = np.linalg.cond(A_well)
print(f"Well-conditioned matrix condition number: {cond_well}")

# Ill-conditioned matrix (Hilbert matrix approximation)
A_ill = np.array([[1, 0.5], [0.5, 0.333]])
cond_ill = np.linalg.cond(A_ill)
print(f"Ill-conditioned matrix condition number: {cond_ill:.1f}")

# Very ill-conditioned matrix
A_very_ill = np.array([[1, 1], [1, 1 + 1e-15]])
cond_very_ill = np.linalg.cond(A_very_ill)
print(f"Very ill-conditioned matrix condition number: {cond_very_ill:.2e}")

# Demonstrate effect of conditioning on solution accuracy
b = np.array([1, 1])
x_exact = np.array([1, 0])  # For A_well, solution should be [1, 0]

# Add small perturbation to b
b_perturbed = b + np.array([1e-10, -1e-10])

x_well = np.linalg.solve(A_well, b)
x_well_pert = np.linalg.solve(A_well, b_perturbed)
error_well = np.linalg.norm(x_well - x_well_pert)

x_ill = np.linalg.solve(A_ill, b)
x_ill_pert = np.linalg.solve(A_ill, b_perturbed)
error_ill = np.linalg.norm(x_ill - x_ill_pert)

print("\nEffect of conditioning on solution stability:")
print(f"Well-conditioned error: {error_well:.2e}")
print(f"Ill-conditioned error: {error_ill:.2e}")
print(f"Error amplification ratio: {error_ill/error_well:.2e}")

# Matrix rank
print("\nMatrix Rank:")
matrices = [
    np.array([[1, 2], [3, 4]]),  # Full rank
    np.array([[1, 2], [2, 4]]),  # Rank deficient
    np.array([[1, 0], [0, 0]])   # Rank 1
]

for i, M in enumerate(matrices):
    rank = np.linalg.matrix_rank(M)
    print(f"Matrix {i+1} rank: {rank}")
    print(M)
    print()


--- Norms and Condition Numbers ---
Vector v: [3 4]
L2 norm (Euclidean): 5.000
L1 norm (Manhattan): 7.000
L∞ norm (Chebyshev): 4.000

Matrix A:
[[1 2]
 [3 4]]
Frobenius norm: 5.477
Spectral norm (L2): 5.465
L1 norm: 6.000
L∞ norm: 7.000

Condition Numbers:
Well-conditioned matrix condition number: 1.0
Ill-conditioned matrix condition number: 19.4
Very ill-conditioned matrix condition number: 3.46e+15

Effect of conditioning on solution stability:
Well-conditioned error: 1.41e-10
Ill-conditioned error: 2.07e-09
Error amplification ratio: 1.46e+01

Matrix Rank:
Matrix 1 rank: 2
[[1 2]
 [3 4]]

Matrix 2 rank: 1
[[1 2]
 [2 4]]

Matrix 3 rank: 1
[[1 0]
 [0 0]]



## Linear Algebra Summary

**Basic Operations:**
- Matrix multiplication: `A @ B` or `np.dot(A, B)`
- Transpose: `A.T`
- Trace: `np.trace(A)`
- Determinant: `np.linalg.det(A)`
- Inverse: `np.linalg.inv(A)`

**Eigenvalues & Eigenvectors:**
- `np.linalg.eig(A)`: Returns eigenvalues and eigenvectors
- Eigenvalue decomposition: `A = Q @ Λ @ Q^(-1)`
- For symmetric matrices: `A = Q @ Λ @ Q^T`

**Linear Systems:**
- Square systems: `np.linalg.solve(A, b)`
- Overdetermined: `np.linalg.lstsq(A, b)` (least squares)
- Underdetermined: `np.linalg.pinv(A) @ b` (minimum norm)

**Matrix Decompositions:**
- SVD: `U, s, Vt = np.linalg.svd(A)`
- QR: `Q, R = np.linalg.qr(A)`
- Cholesky: `L = np.linalg.cholesky(A)` (positive definite matrices)

**Numerical Properties:**
- Norms: `np.linalg.norm(A, ord)`
- Condition number: `np.linalg.cond(A)` (stability indicator)
- Matrix rank: `np.linalg.matrix_rank(A)`

**Key Applications:**
- Principal Component Analysis (PCA)
- Linear regression and least squares
- Image processing and compression
- Quantum mechanics simulations
- Structural analysis and finite element methods
- Machine learning algorithms (SVD, eigendecomposition)

Next: Advanced NumPy Features and Performance Tips